package:
  exclude:
    - .git/**
    - .vscode/**
    - migration/**
    - src/**
    - test/**
    - .prettierrc
    - nest-cli.json
    - nodemon-debug.json
    - nodemon.json
    - ormconfig.dev.json
    - package-lock.json
    - README.md
    - tsconfig.json
    - tsconfig.spec.json
    - tslint.json
    - webpack.config.js

# service: aws-ggt 国内数据库
service: serverless-ggt

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1

functions:
  index:
    handler: dist/serverless.handler
    events:
    - http:
        cors: true
        path: '{proxy+}'
        method: any
